// <auto-generated />
namespace belajar_crud_wpf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_model_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_model_item));
        
        string IMigrationMetadata.Id
        {
            get { return "202003200916083_add_model_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
